import Head from "next/head";
import { useEffect, useState } from "react";
import SkeletonCard from "../components/common/skeletonCard";
import SearchBar from "../components/header/search";
import DropdownMenu from "../components/header/selection";
import CardDisplay from "../components/home/cardDisplay";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  // Fetch data from external API
  const res = await fetch(
    `https://backend.bhalogari.com/api/cars/choose-by-maker/?fbclid=IwAR1Y7CmSWoedY1ZSaCc0LnUqtCatkAttcqSBwJaeZm4hw-N3PxJVNw6Pk4Q&format=json&maker_name`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default function Home({ data }) {
  const [filteredResults, setFilteredResults] = useState([]);
  const [category, setCategory] = useState("");
  const [items, setItems] = useState([]);
  const [filterParam, setFilterParam] = useState("");
  const [searchParam] = useState(category);
  const [isLoading, setLoading] = useState(false);
  const handleChange = (event) => {
    setCategory(event.target.value);
  };

  const allCategory = [
    "SELECT CAR BRAND NAME",
    ...new Set(
      data.results.map((category) => category.car_manufacturer.maker_name)
    ),
  ];

  useEffect(() => {
    setLoading(true);
    fetch(
      `https://backend.bhalogari.com/api/cars/choose-by-maker/?fbclid=IwAR2j2u0KxepVLZMikIcA5H-8CpyDLlttGvY2L2u24_1OepwATRvWgN29KRM&format=json&maker_name=${category}`
    )
      .then((res) => res.json())
      .then((data) => {
        setItems(data.results);
        setLoading(false);
      });
  }, [category]);

  if (!data) return <p>No profile data</p>;
  return (
    <div className={styles.container}>
      <Head>
        <title>car App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-around items-center m-6">
        <DropdownMenu
          allCategory={allCategory}
          handleChange={handleChange}
          category={category}
        />
        <SearchBar />
      </div>

      {isLoading ? (
        <SkeletonCard />
      ) : (
        <div className="flex flex-wrap py-5 justify-center items-center gap-4 ">
          {items.map((data) => (
            <CardDisplay key={data.car_id} data={data} />
          ))}
        </div>
      )}
    </div>
  );
}
